name: Integration Test
on:
  push:
    branches:
      - main
  # workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        uses: OnlineGymnasium/reflect-python-action@main
        with:
          REFLECT_API_KEY: ${{secrets.REFLECT_API_KEY}}
          REFLECT_SUITE_ID: ${{secrets.REFLECT_SUITE_ID}}
